// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjx_YksAUm90JXCrjxG16NKh1zVOgGanM',
    appId: '1:433507603347:web:33f7fb8e8366b24d094e66',
    messagingSenderId: '433507603347',
    projectId: 'umong-8b346',
    authDomain: 'umong-8b346.firebaseapp.com',
    databaseURL: 'https://umong-8b346-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'umong-8b346.firebasestorage.app',
    measurementId: 'G-S3GG4JH6CX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf30lk64TRBwxK2X841B_dIMN5sZd9-Ho',
    appId: '1:433507603347:android:b134152c742fe06a094e66',
    messagingSenderId: '433507603347',
    projectId: 'umong-8b346',
    databaseURL: 'https://umong-8b346-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'umong-8b346.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQNhjcGsK66yzoTAqY5JqS7Gf50byAbEY',
    appId: '1:433507603347:ios:ce64ae11b750ebb3094e66',
    messagingSenderId: '433507603347',
    projectId: 'umong-8b346',
    databaseURL: 'https://umong-8b346-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'umong-8b346.firebasestorage.app',
    iosClientId: '433507603347-p1jcd43r7bjolsoi8ua9d20u6km2lusb.apps.googleusercontent.com',
    iosBundleId: 'com.example.teamproject2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQNhjcGsK66yzoTAqY5JqS7Gf50byAbEY',
    appId: '1:433507603347:ios:ce64ae11b750ebb3094e66',
    messagingSenderId: '433507603347',
    projectId: 'umong-8b346',
    databaseURL: 'https://umong-8b346-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'umong-8b346.firebasestorage.app',
    iosClientId: '433507603347-p1jcd43r7bjolsoi8ua9d20u6km2lusb.apps.googleusercontent.com',
    iosBundleId: 'com.example.teamproject2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjx_YksAUm90JXCrjxG16NKh1zVOgGanM',
    appId: '1:433507603347:web:ffb096271dda74b9094e66',
    messagingSenderId: '433507603347',
    projectId: 'umong-8b346',
    authDomain: 'umong-8b346.firebaseapp.com',
    databaseURL: 'https://umong-8b346-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'umong-8b346.firebasestorage.app',
    measurementId: 'G-TLEY6Z2PM3',
  );
}
